# Generated by Django 5.0.1 on 2024-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default='---', max_length=30),
        ),
    ]
