# Generated by Django 5.0.1 on 2024-01-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
